$ErrorActionPreference = 'Stop'

$sourceUrl = 'https://raw.githubusercontent.com/bitcoin/bips/master/bip-0039/english.txt'
$expectedHash = '187db04a869dd9bc7be80d21a86497d692c0db6abd3aa8cb6be5d618ff757fae'

$words = @(
    ((Invoke-WebRequest -UseBasicParsing $sourceUrl).Content -split "`n") |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ }
)

$normalized = [Text.Encoding]::UTF8.GetBytes($words -join "`n")
$actualHash = [Convert]::ToHexString(
    [Security.Cryptography.SHA256]::HashData($normalized)
).ToLowerInvariant()

if ($actualHash -ne $expectedHash) {
    throw "BIP-39 source hash changed: $actualHash"
}
if ($words.Count -ne 2048) {
    throw "Expected 2,048 words, got $($words.Count)."
}
if (($words | Sort-Object -Unique).Count -ne 2048) {
    throw 'Every dictionary word must be unique.'
}
if ($words.Where({ $_ -notmatch '^[a-z]{3,8}$' }).Count -ne 0) {
    throw 'Every dictionary entry must be a 3-8 letter lowercase word.'
}
if ((Compare-Object $words ($words | Sort-Object)).Count -ne 0) {
    throw 'Dictionary words must be sorted.'
}

$entries = ($words | ForEach-Object { "  '$_'," }) -join "`n"
$output = @"
// Generated by scripts/generate-word-list.ps1. Dictionary order is part of the format.
export const WORDS: readonly string[] = Object.freeze([
$entries
]);
"@

$outputPath = Join-Path $PSScriptRoot '..\src\words.ts'
[IO.File]::WriteAllText(
    $outputPath,
    $output,
    [Text.UTF8Encoding]::new($false)
)
